### ISSUE TITLE
Error while attempting to run example

### ISSUE THREAD

**Issue by louisgv** [johnsonjo4531/read_lines#1]
```
 deno https://raw.githubusercontent.com/johnsonjo4531/read_lines/v2.1.0/examples/input.ts

Download https://raw.githubusercontent.com/johnsonjo4531/read_lines/v2.1.0/examples/input.ts
Compile https://raw.githubusercontent.com/johnsonjo4531/read_lines/v2.1.0/examples/input.ts
Download https://raw.githubusercontent.com/johnsonjo4531/read_lines/v2.1.0/input.ts
Download https://raw.githubusercontent.com/johnsonjo4531/read_lines/v2.1.0/lines.ts
Download https://deno.land/x/io@v0.3.4/bufio.ts
error: Uncaught Other: Import 'https://deno.land/x/io@v0.3.4/bufio.ts' failed: 404 Not Found
► js/errors.ts:33:12
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at maybeThrowError (js/errors.ts:39:15)
    at sendSync (js/dispatch.ts:137:5)
    at fetchSourceFile (js/compiler.ts:134:19)
    at _resolveModule (js/compiler.ts:253:12)
    at js/compiler.ts:369:33
    at resolveModuleNames (js/compiler.ts:367:24)
    at resolveModuleNamesWorker (third_party/node_modules/typescript/lib/typescript.js:89230:127)
    at resolveModuleNamesReusingOldState (third_party/node_modules/typescript/lib/typescript.js:89473:24)
```

**Comment by johnsonjo4531** [comment]
Sorry for the late reply, but @louisgv are you still getting this error with v3.0.0? Try running this:

```bash
deno https://raw.githubusercontent.com/johnsonjo4531/read_lines/v3.0.0/examples/input.ts
```

**Comment by phil294** [comment]
Yes @johnsonjo4531, the error is still there with v3.0.0. https://deno.land/std@v0.12/io/bufio.ts also doesnt exist. Why not get rid of the version number? I'll submit a pull request in a second
